### ISSUE TITLE
Help me for installation

### ISSUE THREAD

**Issue by MiltonBalaOfficial** [WillNilges/inkpath#36] opened 2024-12-22 06:14 UTC
![image](https://github.com/user-attachments/assets/8a1195f5-e064-431c-b831-9c15264c3d36)

**Comment by WillNilges** [comment] 2024-12-24 14:52
Thanks for trying it. Yeah, I ran into this issue a lot. The reason for this is that Xournal++'s executable cannot find the dlls that are bundled with the plugin. Can you send me a screenshot of `C:\Program Files\Xournal++\share\xournalpp\plugins\ImageTranscription` to make sure all the DLLs are present, and of your Path? I think you may have forgotten to run the `install.ps1` script.

To check your path, type Win+R and type `sysdm.cpl`, Go to Advanced > Enviornment Variables > Path > Edit. If you see `C:\Program Files\Xournal++\share\xournalpp\plugins\ImageTranscription` in there, then the issue is probably somewhere else. If not, try adding that to the Path.

https://github.com/WillNilges/inkpath/tree/wdn/windows?tab=readme-ov-file#installation-on-windows

**Comment by MiltonBalaOfficial** [comment] 2024-12-24 18:21
> I think you may have forgotten to run the `install.ps1` script.

No, I ran it several times. There might be an issue when running the file, I don't know exactly.

> If not, try adding that to the Path.

After adding the path, the issue was resolved. However, I noticed that selecting an image didn't produce any visible effect initially. Suspecting the app might require a refresh, I added the `app.refreshPage()` API call after the stroke insertion. This resolved the problem, and now the effect is visible.

Thank you for developing such a wonderful plugin! I look forward to seeing it mature and reach its full potential."

**Comment by WillNilges** [comment] 2024-12-24 18:49
Oh, awesome! Glad you figured it out 😄 Enjoy the plugin!

Sorry about the powershell script not working, guess I need to debug that some more :/

Thank you for fixing that page update bug! That was a known issue that I haven't looked into yet. Would you like to submit a pull request to update the Lua script for `app.refreshPage()`?

**Comment by WillNilges** [comment] 2024-12-25 22:04
:wave: @MiltonBalaOfficial Closing this issue now. Feel free to re-open it if you need more support :)

**Closed by WillNilges** 2024-12-25 22:04 UTC
